language: csharp
mono: none
dotnet: 2.1.300
dist: trusty
sudo: "required"
before_install:
  - sudo apt-get update
install:
 - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
script:
 - dotnet restore ./Lib/Protoacme/ProtoAcme.csproj
 - dotnet build ./Lib/Protoacme/ProtoAcme.csproj -c Release
 - dotnet pack ./Lib/Protoacme/ProtoAcme.csproj -c Release -o ./nuget-package /p:Version=1.0.$TRAVIS_BUILD_NUMBER
 - dotnet nuget push ./Lib/Protoacme/nuget-package/ProtoAcme.1.0.$TRAVIS_BUILD_NUMBER.nupkg -k $NUGET_API_KEY -s https://www.nuget.org/api/v2/package
